package com.coherentlogic.rproject.integration.rcoboldi.api;

import java.io.File;
import java.io.IOException;

import com.coherentlogic.rproject.integration.rcoboldi.api.JCopyBookConverter.PassThroughUpdateFieldName;

import net.sf.JRecord.Common.Conversion;
import net.sf.JRecord.cbl2csv.Cobol2Csv;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 
Not all copybook files can be converted into CSV.

Single Record Type files can be converted to CSV.
Complicated Multi-Record files will NOT map to CSV.

If you have the Sourceforge JRecord download there are the following directories

* SampleFiles
* CopyBook\Cobol

The following File/Copybook combinarions should work well:

Copybook File

AmsLocation.cbl Ams_LocDownload_20041228.txt - Standard Text file
DTAR020.cbl DTAR020.bin - Mainframe Binary File (Fixed Width
DTAR107.cbl DTAR107.bin

If you are using supplied Cobol2Csv program the scripts would be like (Windows):

For AmsLocation.cbl :

../lib/Cobol2Csv.bat -C G:/Users/ExampleUserTst01/RecordEditor_HSQL/CopyBook/Cobol/AmsLocation.cbl ^
-Delimiter , ^
-Quote doublequote ^
-IFS Text ^
-I G:/Users/ExampleUserTst01/RecordEditor_HSQL/SampleFiles/Ams_LocDownload_20041228.txt ^
-O G:/Users/ExampleUserTst01/RecordEditor_HSQL/SampleFiles/Ams_LocDownload_20041228.txt.csv

For DTAR020:

../lib/Cobol2Csv.bat -C G:/Users/ExampleUserTst01/RecordEditor_HSQL/CopyBook/Cobol/DTAR020.cbl ^
-Delimiter , ^
-Quote doublequote ^
-IFS Fixed_Length ^
-IC cp037 ^
-I G:/Users/ExampleUserTst01/RecordEditor_HSQL/SampleFiles/DTAR020.bin ^
-O G:/Users/ExampleUserTst01/RecordEditor_HSQL/SampleFiles/DTAR020.bin.csv

Also RecordEditor/RecsvEditor can generate Cobol2Csv Scripts from a copybook/file.

 * -----
./Source/OtherSource/JRecord_Cobol2Json_package/cobolToJson/src/net/sf/JRecord/cbl2json/zExampleGen/Dtar020ToJson.java

  * *------------- Keep this notice in your final code ---------------
  * *   This code was generated by JRecord projects CodeGen program
  * *            on the: 20 Jun 2016 13:43:8
  * *     from Copybook: DTAR020.cbl
  * *           Dialect: FMT_MAINFRAME
  * *          Template: javaCbl2Json
  * *             Split: SPLIT_NONE
  * * File Organization: IO_FIXED_LENGTH
  * *              Font: cp037
 *
 */
public class Main {

    private static final Logger log = LoggerFactory.getLogger(Main.class);

    static final String PATH_PREFIX = "/Users/thospfuller/development/projects/rcoboldi-gh/rcoboldi/java/rcoboldi-core/";

    static final String TEST_RESOURCES_PREFIX = PATH_PREFIX + "src/test/resources/";

    static final String COBRIX_DATA_PREFIX = TEST_RESOURCES_PREFIX + "/cobrix-data/";

    static String executeExample1 (JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (TEST_RESOURCES_PREFIX + "example1/DTAR020.cbl").toString();
        var inFile       = new File (TEST_RESOURCES_PREFIX + "example1/DTAR020.bin").toString();

//        var copyBookFile = "/Users/thospfuller/development/projects/rcobol/download/Examples/SchemaCompare/cobol_copybooks/DTAR020.cbl";
//        var inFile       = "/Users/thospfuller/development/projects/rcobol/download/Source/JRecord/src/net/sf/JRecord/zTest/Common/SampleFiles/DTAR020.bin";

        var inFont = "cp037";

        /**
         * https://sourceforge.net/p/jrecord/wiki/Home/
         * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
         * https://github.com/svn2github/jrecord/blob/master/Source/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java -- binFormat is the dialect.
         *
         * String copyBookFile, String font, String sep, String quote, IUpdateFieldName updateFldName
         */
        var result = jCopyBookConverter.readCopyBookAsString (
            copyBookFile,
            inFile,
            "Fixed Length Binary",
            inFont,
            1, // MAINFRAME
            new PassThroughUpdateFieldName ()
        );

        return result;
    }

    static String executeExample2 (JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (TEST_RESOURCES_PREFIX + "example2/DTAR107.cbl").toString();
        var inFile       = new File (TEST_RESOURCES_PREFIX + "example2/DTAR107.bin").toString();

        var inFont = "cp037";

        /**
         * https://sourceforge.net/p/jrecord/wiki/Home/
         * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
         * https://github.com/svn2github/jrecord/blob/master/Source/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java -- binFormat is the dialect.
         *
         * String copyBookFile, String font, String sep, String quote, IUpdateFieldName updateFldName
         */
        var result = jCopyBookConverter.readCopyBookAsString (
            copyBookFile,
            inFile,
            "Fixed Length Binary",
            inFont,
            1, // MAINFRAME
            new PassThroughUpdateFieldName ()
        );

        return result;
    }

    static String executeExample3 (JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (TEST_RESOURCES_PREFIX + "example3/AmsLocation.cbl").toString();
        var inFile       = new File (TEST_RESOURCES_PREFIX + "example3/Ams_LocDownload_20041228.txt").toString();

        var inFont = Conversion.DEFAULT_ASCII_CHARSET;//"cp037";

        /**
         * https://sourceforge.net/p/jrecord/wiki/Home/
         * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
         * https://github.com/svn2github/jrecord/blob/master/Source/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java -- binFormat is the dialect.
         *
         * String copyBookFile, String font, String sep, String quote, IUpdateFieldName updateFldName
         */
        var result = jCopyBookConverter.readCopyBookAsString (
            copyBookFile,
            inFile,
            "Text",
            inFont,
            1, // MAINFRAME
            new PassThroughUpdateFieldName ()
        );

        return result;
    }

    static String executeCobrixTest1(JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (COBRIX_DATA_PREFIX + "test1_copybook.cob").toString();
        var inFile       = new File (COBRIX_DATA_PREFIX + "test1_data/example.bin").toString();

        var inFont = "cp037";

        /**
         * https://sourceforge.net/p/jrecord/wiki/Home/
         * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
         * https://github.com/svn2github/jrecord/blob/master/Source/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java -- binFormat is the dialect.
         *
         * String copyBookFile, String font, String sep, String quote, IUpdateFieldName updateFldName
         */
        var result = jCopyBookConverter.readCopyBookAsString (
                copyBookFile,
                inFile,
                "Fixed Length Binary",
                inFont,
                1, // MAINFRAME
                new PassThroughUpdateFieldName ()
        );

        return result;
    }

    static String executeCobrixTest2(JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (COBRIX_DATA_PREFIX + "test2_copybook.cob").toString();
        var inFile       = new File (COBRIX_DATA_PREFIX + "test2_data/example.bin").toString();

        var inFont = "cp037";

        /**
         * https://sourceforge.net/p/jrecord/wiki/Home/
         * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
         * https://github.com/svn2github/jrecord/blob/master/Source/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java -- binFormat is the dialect.
         *
         * String copyBookFile, String font, String sep, String quote, IUpdateFieldName updateFldName
         */
        var result = jCopyBookConverter.readCopyBookAsString (
                copyBookFile,
                inFile,
                "Fixed Length Binary",
                inFont,
                1, // MAINFRAME
                new PassThroughUpdateFieldName ()
        );

        return result;
    }

    static String executeCobrixTest21(JCopyBookConverter jCopyBookConverter) throws IOException {

        var copyBookFile = new File (COBRIX_DATA_PREFIX + "test21_copybook.cob").toString();
        var inFile       = new File (COBRIX_DATA_PREFIX + "test21_data/data.dat").toString();

        var result = jCopyBookConverter.readCopyBookAsString (
                copyBookFile,
                inFile,
                "Text",
                "cp1252",
                1, // MAINFRAME
                new PassThroughUpdateFieldName ()
        );

        return result;
    }

    /**
     * /Users/thospfuller/development/projects/rcoboldi-gh/rcoboldi/java/rcoboldi-core/src
     * /Users/thospfuller/development/projects/rcoboldi-gh/rcoboldi/java/
     * @param args
     * @throws IOException
     */
    public static void test(String[] args) throws IOException {

        var jCopyBookConverter = new JCopyBookConverter ();

        System.out.println ("Example 1         : " + executeExample1 (jCopyBookConverter));
        System.out.println ("Example 2         : " + executeExample2 (jCopyBookConverter));
        System.out.println ("Example 3         : " + executeExample3 (jCopyBookConverter));
        System.out.println ("Example Cobrix 1  : " + executeCobrixTest1 (jCopyBookConverter));
        System.out.println ("Example Cobrix 2  : " + executeCobrixTest2 (jCopyBookConverter));
        System.out.println ("Example Cobrix 21 : " + executeCobrixTest21 (jCopyBookConverter));
    }

    /**
     * Method delegates to {Cobol2Csv#main}.
     *
     * When running Main in IntelliJ Idea select "Include dependencies with 'Provided' scope."
     * in the middle of the screen otherwise you'll see SLF4J related CNF exceptions at runtime.
     *
     * https://github.com/bmTas/JRecord/blob/master/Source/JRecord_Utilities/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java
     *
     * https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/
     */
    public static void main(String[] args) throws IOException {

        log.info ("The main method delegates to Cobol2Csv#main");
        log.info ("See:");
        log.info ("https://sourceforge.net/p/jrecord/wiki/Cobol2Csv%2C%20Csv2Cobol/");
        log.info ("and");
        log.info ("https://github.com/bmTas/JRecord/blob/master/Source/JRecord_Utilities/JRecord_Cbl2Csv/src/net/sf/JRecord/cbl2csv/Cobol2Csv.java");
        log.info ("main: method begins; args: " + args);

        Cobol2Csv.main(args);

        log.info ("main: method ends.");
    }
}
